import "./globals.css";
import Providers from "@/redux/Providers";
import { Vazirmatn } from "next/font/google";
const vazir = Vazirmatn({ subsets: ["arabic"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={vazir.className}>{children}</body>
    </html>
  );
}
